In [20]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [63]:
# Read Data from CSV 

train_data = pd.read_csv('D:\Public\Jyothsna\Python\Soc Softech\Data Processing\DS\Train.txt')
train_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [64]:
# Check out teh Missing values

train_data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
 srv_serror_rate               0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
attack                         0
last_flag                      0
dtype: int64

In [65]:
# remove the missing  values

train_data.dropna(inplace=True)
train_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [66]:
train_data.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       ' srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'attack', 'last_flag'],
      dtype='object')

In [67]:
# Categorical Values

# There is no YES/NO and True/False values

# Column = protocol_type

dummy = pd.get_dummies(train_data['protocol_type'])
dummy

train_data = pd.concat([train_data,dummy],axis=1)
data.head()

train_data.drop(columns='protocol_type',inplace=True)
train_data.head()

,duration,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag,icmp,tcp,udp
0,0,ftp_data,SF,491,0,0,0,0,0,0,...,0.00,0.00,0.00,0.05,0.00,normal,20,0,1,0
1,0,other,SF,146,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,normal,15,0,0,1
2,0,private,S0,0,0,0,0,0,0,0,...,0.00,1.00,1.00,0.00,0.00,neptune,19,0,1,0
3,0,http,SF,232,8153,0,0,0,0,0,...,0.04,0.03,0.01,0.00,0.01,normal,21,0,1,0
4,0,http,SF,199,420,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,normal,21,0,1,0

In [68]:
# Column = service

dummy = pd.get_dummies(train_data['service'])
dummy

train_data = pd.concat([train_data,dummy],axis=1)
train_data.head()

train_data.drop(columns='service',inplace=True)
train_data.head()

,duration,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,...,telnet,tftp_u,tim_i,time,urh_i,urp_i,uucp,uucp_path,vmnet,whois
0,0,SF,491,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,SF,146,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,S0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,SF,232,8153,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,SF,199,420,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [69]:
# Column = flag

dummy = pd.get_dummies(train_data['flag'])
dummy

train_data = pd.concat([train_data,dummy],axis=1)
train_data.head()

train_data.drop(columns='flag',inplace=True)
train_data.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,REJ,RSTO,RSTOS0,RSTR,S0,S1,S2,S3,SF,SH
0,0,491,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [70]:
# Column = attack

dummy = pd.get_dummies(train_data['attack'])
dummy

train_data = pd.concat([train_data,dummy],axis=1)
train_data.head()

train_data.drop(columns='attack',inplace=True)
train_data.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,phf,pod,portsweep,rootkit,satan,smurf,spy,teardrop,warezclient,warezmaster
0,0,491,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
import warnings
warnings.filterwarnings('ignore')

# Initialize the Scaler

scaler = StandardScaler()


# To scale data

train_data1 = scaler.fit_transform(train_data)
train_data1

array([[-0.11024922, -0.0076786 , -0.00491864, ..., -0.08444749,
        -0.08435209, -0.01260117],
       [-0.11024922, -0.00773737, -0.00491864, ..., -0.08444749,
        -0.08435209, -0.01260117],
       [-0.11024922, -0.00776224, -0.00491864, ..., -0.08444749,
        -0.08435209, -0.01260117],
       ...,
       [-0.11024922, -0.00738219, -0.00482315, ..., -0.08444749,
        -0.08435209, -0.01260117],
       [-0.11024922, -0.00776224, -0.00491864, ..., -0.08444749,
        -0.08435209, -0.01260117],
       [-0.11024922, -0.00773652, -0.00491864, ..., -0.08444749,
        -0.08435209, -0.01260117]])

In [72]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

train_data2 = min_max_scaler.fit_transform(train_data)
train_data2

array([[0.00000000e+00, 3.55806412e-07, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.05799870e-07, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 1.61670897e-06, 2.93143779e-07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.09423153e-07, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

Working on Test Dataset

In [73]:
# Read Data from CSV 

test_data = pd.read_csv('D:\Public\Jyothsna\Python\Soc Softech\Data Processing\DS\Test.txt')
test_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [74]:
# finding the missing values

test_data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
 srv_serror_rate               0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
attack                         0
last_flag                      0
dtype: int64

There is  no missing values

In [75]:
test_data.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       ' srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'attack', 'last_flag'],
      dtype='object')

In [76]:
# working on categorical data

# There is no YES/NO and True/False 

protocol_type = pd.get_dummies(test_data['protocol_type'])
service = pd.get_dummies(test_data['service'])
flag = pd.get_dummies(test_data['flag'])
attack = pd.get_dummies(test_data['attack'])

test_data = pd.concat([test_data,protocol_type,service,flag,attack],axis=1)

test_data.drop(columns=['protocol_type','service','flag','attack'],inplace=True)
test_data.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,snmpgetattack,snmpguess,sqlattack,teardrop,udpstorm,warezmaster,worm,xlock,xsnoop,xterm
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,12983,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,20,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,15,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
import warnings
warnings.filterwarnings('ignore')

# Initialize the Scaler

scaler = StandardScaler()


# To scale data

test_data1 = scaler.fit_transform(test_data)
test_data1

array([[-0.15553409, -0.02198811, -0.09689597, ..., -0.01998446,
        -0.0133215 , -0.02402047],
       [-0.15553409, -0.02198811, -0.09689597, ..., -0.01998446,
        -0.0133215 , -0.02402047],
       [-0.15411277,  0.0054731 , -0.09689597, ..., -0.01998446,
        -0.0133215 , -0.02402047],
       ...,
       [-0.15553409,  0.09337309,  0.29492588, ..., -0.01998446,
        -0.0133215 , -0.02402047],
       [-0.15553409, -0.02189927, -0.0949166 , ..., -0.01998446,
        -0.0133215 , -0.02402047],
       [-0.15553409, -0.02198811, -0.09689597, ..., -0.01998446,
        -0.0133215 , -0.02402047]])

In [78]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

test_data2 = min_max_scaler.fit_transform(test_data)
test_data2

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.46530365e-05, 2.06651271e-04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 8.68116792e-04, 6.17715522e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.68516782e-07, 3.12052585e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])